service-values:
  em-srv:
    type: enterprise-messaging
    instance: d86811ac-6642-4265-9d00-2954577b98db
    key: keyems
  destination-srv:
    type: destination
    instance: 5de5687f-1b0e-4862-95b0-d20a031b15cf
    key: destkey
secret-values:
  destination-name:
    name:
      name: RegisteredoData
      attachmentSrvApi: API_CV_ATTACHMENT_SRV
      businessPartnerSrvApi: API_BUSINESS_PARTNER
      businessObjectTypeName: BUS1006
config-values:
  amqp-service-config:
    amqp:
      incoming:
        inp1:
          sourceAddress: refapps/bpems/abc/refapps/bpems/abc/MyQueue
          sndSettleMode: 0
          rcvSettleMode: 0
          maxLinkCredit: 50
    bind:
      rules:
        - filter:
            incoming: inp1
          action:
            function: qrcodegenerator
            failure: accept
            content: application/json
